import { StyleSheet } from 'react-native';

const indexCSS = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgb(80, 80, 80)',
    },
    presentButton: {
      position: 'absolute',
      top: 100,
      height: '10%',
      width: '90%',
      backgroundColor: 'rgb(50, 50, 50)',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
      borderColor: 'rgb(50, 50, 50)',
      borderWidth: 1,
      marginHorizontal: 20,
    },
    highlightButton: {
      height: '45%',
      width: '90%',
      backgroundColor: 'rgb(50, 50, 50)',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
      borderColor: 'rgb(50, 50, 50)',
      borderWidth: 1,
      marginTop: 20,
    },
    bottomButtonContainer: {
      position: 'absolute',
      bottom: 20,
      height: '20%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '90%',
    },
    bottomButton: {
      width: '40%',
      height: '100%',
      backgroundColor: 'rgb(50, 50, 50)',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 5,
      borderColor: 'rgb(50, 50, 50)',
      borderWidth: 1,
    },
    slideContainer: {
      position: 'absolute',
      top: 40,
      right: 0,
      height: 50,
      backgroundColor: 'rgb(50, 50, 50)',
      borderRadius: 5,
      flexDirection: 'row',
      alignItems: 'center',
    },
    inputGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      paddingHorizontal: 5,
    },
    input: {
      flex: 1,
      backgroundColor: '#ffffff',
      height: 40,
      paddingLeft: 10,
      borderTopLeftRadius: 5,
      borderBottomLeftRadius: 5,
    },
    saveButton: {
      width: 50,
      height: 40,
      backgroundColor: 'rgb(80, 80, 80)',
      justifyContent: 'center',
      alignItems: 'center',
      borderTopRightRadius: 5,
      borderBottomRightRadius: 5,
    },
    toggleButton: {
      position: 'absolute',
      top: 40,
      right: -10,
      width: 50,
      height: 50,
      backgroundColor: 'rgb(60, 60, 60)',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 20,
      zIndex: 1,
    },
});

export default indexCSS;